### ISSUE TITLE
Contrast/Brightness/Gamma

### ISSUE THREAD

**Issue by LukasThyWalls** [SuiMachine/The-Thing-Wrapper#1]
I have searched where to talk directly with the developer of this wrapper, and i think here is the only way to make it. I don't know if i can put some issues with the wrapper for The Thing to make some upgrades or not because the issue tracker is empty. Maybe you are not opened for them.

Anyway: 

The main issue is with the contrast/brightness. The game is too dark in a lot of places, and there is not gamma/brightness/contrast change in settings or the wrapper's ini.

I used dgVoodoo to put contrast between 80-90% (100% is the original) and it looks better, but, can't use dgVoodoo and this wrapper at the same time because use the same kind de DLL (D3D8.DLL).

Also if the "Load Game" in in-game menu isn't working, maybe is better to not to be there. Maybe is not possible to get rid of it.

Thanks.

**Comment by SuiMachine** [comment]
I should probably make it clearer, but you're not suppose to use both d3d8.dll and dinput8.dll together. As in, I developed it firstly to hook dinput8.dll and then reworked it to d3d8.dll to have access to D3D8 calls. If you're using dgVoodoo however, it's probably best if you use dinput8.dll instead.

What you need to do is download **dinput8.dll** and put it in the game's folder. Then you take the **d3d8.ini** and rename it to **dinput8.ini** - everything from the config aside from the elements in section of [D3D8] will be loaded, as it was with d3d8 wrapper. Then you should be able to use dgVoodoo to wrap D3D8 and since it has quite extensive settings, I guess it should not be a problem to enforce at least Vsync and anisotropic settings with it.

As for Load Game option not working, it's not only not working in wrapper, but in general if you enable it via registry.

**Comment by SuiMachine** [comment]
I made some changes to repo and made an actual release with Readme in it point it out.
https://github.com/SuiMachine/The-Thing-Wrapper/releases/latest

**Comment by LukasThyWalls** [comment]
We tested the last version and everything seems to work. We are playing The Thing for Youtube (no public yet) and the first episode is with the original patch and looks dark, the second is edited to increase brightness, and the third have dgVoodoo alongside with the patch with only change contrast at 85%. Here are two screenshots from the same room to look the change: 

![TheThing 2019-03-27 01-10-13-09 avi_snapshot_07 30_ 2019 03 28_22 26 41](https://user-images.githubusercontent.com/1467366/55194059-e29ff480-51a8-11e9-9496-231ea101ce64.jpg)
![TheThing 2019-03-28 19-38-45-48 avi_snapshot_00 01_ 2019 03 28_22 26 52](https://user-images.githubusercontent.com/1467366/55194060-e29ff480-51a8-11e9-8412-6fdba44c9693.jpg)

Thanks!
